stages:
  preprocess:
    cmd: python src/data_pipeline.py --params params.yaml
    deps:
      - src/data_pipeline.py
      - params.yaml
      - data/raw/train.csv
      - data/raw/test.csv
      - data/raw/train-images.idx3-ubyte
      - data/raw/train-labels.idx1-ubyte
      - data/raw/t10k-images.idx3-ubyte
      - data/raw/t10k-labels.idx1-ubyte
    outs:
      - data/processed/train.parquet        # Titanic processed
      # - data/processed/mnist_train.parquet # MNIST processed train
      # - data/processed/mnist_test.parquet  # MNIST processed test

  split:
    cmd: python src/split.py data/processed/train.parquet data/processed/train_train.parquet data/processed/train_val.parquet --params params.yaml
    deps:
      - src/split.py
      - params.yaml
      - data/processed/train.parquet
    outs:
      - data/processed/train_train.parquet
      - data/processed/train_val.parquet

  train:
    cmd: python src/train.py --train data/processed/train_train.parquet --val data/processed/train_val.parquet --params params.yaml
    deps:
      - src/train.py
      - params.yaml
      - data/processed/train_train.parquet
      - data/processed/train_val.parquet
      # - data/processed/mnist_train.parquet
      # - data/processed/mnist_test.parquet
    outs:
      - models/titanic_model
      # - models/mnist_model

  evaluate:
    cmd: python src/evaluate.py --val data/processed/train_val.parquet --model models/titanic_model --params params.yaml
    deps:
      - src/evaluate.py
      - params.yaml
      - models/titanic_model
      - data/processed/train_val.parquet
    metrics:
      - metrics.json
