dataset:
  type: "titanic"  # switch to "titanic" or "mnist"

  titanic:
    raw_path: "data/raw/train.csv"
    processed_path: "data/processed/train.parquet"

  mnist:
    raw_images: "data/raw/train-images.idx3-ubyte"
    raw_labels: "data/raw/train-labels.idx1-ubyte"
    test_images: "data/raw/t10k-images.idx3-ubyte"
    test_labels: "data/raw/t10k-labels.idx1-ubyte"
    processed_train: "data/processed/mnist_train.parquet"
    processed_test: "data/processed/mnist_test.parquet"

features:
  titanic:
    numerical: ["Age", "SibSp", "Parch", "Fare", "FamilySize", "IsAlone"]
    categorical: ["Sex", "Embarked", "Title"]
    label: "Survived"

  mnist:
    label: "label"  # column name returned by prepare_mnist

model:
  titanic:
    numTrees: 100
    maxDepth: 5

  mnist:
    maxIter: 10
